# Generated by Django 3.1 on 2020-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_movie_count',
            field=models.IntegerField(default=0),
        ),
    ]
