# Generated by Django 3.1 on 2020-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_movies', '0002_auto_20200806_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_99popularity',
            new_name='_99popularity',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_director',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_imdb_score',
            new_name='imdb_score',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='movie_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_genre',
        ),
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default=[], max_length=300),
        ),
    ]
