# Generated by Django 3.1 on 2020-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_movies', '0003_auto_20200806_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
