# Generated by Django 3.1 on 2020-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_movies', '0004_auto_20200806_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.TextField(null=True),
        ),
    ]
