# Generated by Django 3.1 on 2020-08-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_movies', '0005_auto_20200806_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='_99popularity',
            new_name='movie_99popularity',
        ),
    ]
